language: python
python:
  - "2.6"
  - "2.7"
before_install: sudo apt-get install -qq libhdf5-serial-dev libblas-dev gfortran liblapack-dev
# command to install dependencies. pip needs to be updated to make h5py install
# correctly. The directory changes are to prevent the local setup.cfg from
# affecting the pip installs.
install:
  - "(cd ~ && pip install -U pip setuptools)"
  - "(cd ~ && travis_wait pip install -r $OLDPWD/requirements.txt)"
# command to run tests
script: nosetests katsdpingest.test.test_telescope_model
